### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [4]:
import numpy as np
import random 


In [8]:
arr=np.array([random.randint(1,20) for _ in range(25)]).reshape(5,5)
print(arr)

[[ 3 20 14 12  4]
 [15  5 17  9 12]
 [ 5  6 17 19 20]
 [10 15 19 20  9]
 [14  9  8  6 13]]


In [12]:
arr[:, 2] = 1
arr

array([[ 3, 20,  1, 12,  4],
       [15,  5,  1,  9, 12],
       [ 5,  6,  1, 19, 20],
       [10, 15,  1, 20,  9],
       [14,  9,  1,  6, 13]])

In [14]:
np.fill_diagonal(arr,0)
arr

array([[ 0, 20,  1, 12,  4],
       [15,  0,  1,  9, 12],
       [ 5,  6,  0, 19, 20],
       [10, 15,  1,  0,  9],
       [14,  9,  1,  6,  0]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [18]:
arr=np.random.randint(1,36,(6,6))
arr

array([[26, 23, 25, 13,  1, 35],
       [13,  3, 23, 31, 16, 32],
       [22, 25,  2,  5, 21, 35],
       [17, 14,  1, 17,  8, 21],
       [23,  6, 26, 22, 25, 25],
       [34, 12, 29,  3, 19, 34]])

In [19]:
arr[2:5,1:4]

array([[25,  2,  5],
       [14,  1, 17],
       [ 6, 26, 22]])

In [20]:
## 2
arr2=np.random.randint(1,25,(5,5))

In [23]:
border_ele=np.concatenate((arr[:,0],arr[0,:],arr[:,-1],arr[-1,:]))
border_ele

array([26, 13, 22, 17, 23, 34, 26, 23, 25, 13,  1, 35, 35, 32, 35, 21, 25,
       34, 34, 12, 29,  3, 19, 34])

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [29]:
rans=[random.randint(1,19) for _ in range(16)]
arr1=np.array(rans).reshape(4,4)
arr1

array([[ 2,  7, 10, 13],
       [ 5, 14, 19,  7],
       [15,  9,  6, 15],
       [ 6, 18, 18, 17]])

In [30]:
arr2=np.random.randint(1,23,(4,4))
arr2

array([[13, 20, 16, 14],
       [22,  2, 22, 16],
       [19,  2,  3,  2],
       [18, 11,  3, 16]])

In [31]:
arr1+arr2

array([[15, 27, 26, 27],
       [27, 16, 41, 23],
       [34, 11,  9, 17],
       [24, 29, 21, 33]])

In [32]:
arr1*arr2

array([[ 26, 140, 160, 182],
       [110,  28, 418, 112],
       [285,  18,  18,  30],
       [108, 198,  54, 272]])

In [33]:
arr1/arr2


array([[0.15384615, 0.35      , 0.625     , 0.92857143],
       [0.22727273, 7.        , 0.86363636, 0.4375    ],
       [0.78947368, 4.5       , 2.        , 7.5       ],
       [0.33333333, 1.63636364, 6.        , 1.0625    ]])

In [34]:
arr1//arr2

array([[0, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 4, 2, 7],
       [0, 1, 6, 1]])

In [35]:
arr2=np.random.randint(1,16,(4,4))
arr2

array([[ 8,  9, 14,  5],
       [ 6, 10,  6,  2],
       [ 3,  5,  1, 11],
       [ 7,  5,  5, 10]])

In [38]:
## rowise sum
sumi= map(sum,(arr2[i,:] for i in range(len(arr2))))
list(sumi)


[36, 24, 20, 27]

In [40]:
np.sum(arr2,axis=1)

array([36, 24, 20, 27])

In [41]:
np.sum(arr,axis=0)

array([135,  83, 106,  91,  90, 182])

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [42]:
arr1=np.random.randint(1,24,(5,5))
np.mean(arr)


19.083333333333332

In [43]:
np.std(arr)

10.258803807245537

In [44]:
np.median(arr)

21.5

In [45]:
np.var(arr)

105.24305555555553

In [56]:
### normalizat5ion

arr1=np.random.randint(1,9,(3,3))
arr1

array([[4, 2, 1],
       [8, 3, 4],
       [4, 5, 3]])

In [57]:
np.mean(arr1)

3.7777777777777777

In [58]:
np.std(arr1)

1.872477727372524

In [62]:
print(arr1)
zscore=(arr1-np.mean(arr1))/(np.std(arr1))
print(zscore)
print(zscore.mean())
zscore.std()



[[4 2 1]
 [8 3 4]
 [4 5 3]]
[[ 0.11867817 -0.94942533 -1.48347707]
 [ 2.25488515 -0.41537358  0.11867817]
 [ 0.11867817  0.65272991 -0.41537358]]
4.9343245538895844e-17


1.0000000000000002

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [63]:
arr=np.random.randint(1,55,(3,3))
inverse=np.linalg.inv(arr)
det_A=np.linalg.det(arr)
print(inverse,det_A)


[[-0.02056743  0.00080228  0.03318503]
 [ 0.03836336 -0.01568084 -0.01225294]
 [-0.00279581  0.02965988 -0.01558359]] 41133.00000000004


In [64]:
egvalue,eigvector=np.linalg.eig(arr)

In [65]:
egvalue,eigvector

(array([ 84.84300392 +0.j       , -15.42150196+15.7159276j,
        -15.42150196-15.7159276j]),
 array([[ 0.59229265+0.j       ,  0.35790927+0.389308j ,
          0.35790927-0.389308j ],
        [ 0.57586106+0.j       , -0.64272806+0.j       ,
         -0.64272806-0.j       ],
        [ 0.56353656+0.j       ,  0.27458496-0.4815018j,
          0.27458496+0.4815018j]]))

In [66]:
## matrix multiplication 

In [67]:
A=np.random.randint(1,5,(2,3))
B=np.random.randint(2,5,(3,2))
A @ B

array([[34, 40],
       [32, 40]])

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [68]:
arr=np.random.randint(1,9,(3,3)).reshape(1,9)
arr

array([[8, 1, 2, 8, 8, 7, 2, 5, 2]])

In [69]:
arr.reshape(9,1)

array([[8],
       [1],
       [2],
       [8],
       [8],
       [7],
       [2],
       [5],
       [2]])

In [71]:
arr=np.random.randint(1,645,(5,5)).reshape(-1)
arr

array([121, 535, 354,  79, 326, 154, 430, 385, 588,  22, 386, 615, 468,
        11, 502, 131, 575, 558, 326, 347, 123, 555, 242,  98, 181])

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [2]:
import numpy as np
arr=np.random.randint(1,34,(5,5))
## fancy indexing [1,5,5]  or [[rows],[cols]] or [[row,col],[]]
rows=[0,0,4,4]
cols=[4,0,4,0]
arr[rows,cols]


array([ 7,  9,  2, 32])

In [8]:
arr=np.random.randint(1,34,(4,4))
## fancy indexing [1,5,5]  or [[rows],[cols]] or [[row,col],[]]
rows=[0,0,4,4]
cols=[4,0,4,0]
print(arr)
arr[arr>10]=10
arr

[[29 22 19 14]
 [16 26 17 28]
 [15 13 20 32]
 [19  9 22 28]]


array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10,  9, 10, 10]])

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [3]:
student_dtype=np.dtype([('name','U10'),('age','i4'),('wight','f4')])
students=np.array([('amar',10,54.2),('akash',23,542.2),('vikash',24,542.45)],dtype=student_dtype)

In [4]:
print(students)

[('amar', 10,  54.2 ) ('akash', 23, 542.2 ) ('vikash', 24, 542.45)]


In [5]:
print(students['name'])

['amar' 'akash' 'vikash']


In [6]:
idx=np.argsort(students['age'])
sorted_students=students[idx]
sorted_students

array([('amar', 10,  54.2 ), ('akash', 23, 542.2 ),
       ('vikash', 24, 542.45)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('wight', '<f4')])

In [7]:
##2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.
arr_dtype=np.dtype([('x','i8'),('y','i8')])

In [8]:
arr=np.array([(3,2),(3,5),(5,2),(5,2)],dtype=arr_dtype)

In [9]:

x=arr['x']
y=arr['y']
x

array([3, 3, 5, 5], dtype=int64)

In [10]:
dx=x[:,None]
dx

array([[3],
       [3],
       [5],
       [5]], dtype=int64)

In [11]:
dy=y[:,None]
dy

array([[2],
       [5],
       [2],
       [2]], dtype=int64)

In [12]:
dx=dx-x
dy=dy-y
dx,dy

(array([[ 0,  0, -2, -2],
        [ 0,  0, -2, -2],
        [ 2,  2,  0,  0],
        [ 2,  2,  0,  0]], dtype=int64),
 array([[ 0, -3,  0,  0],
        [ 3,  0,  3,  3],
        [ 0, -3,  0,  0],
        [ 0, -3,  0,  0]], dtype=int64))

In [14]:
sumi=dx+dy

In [15]:
np.sqrt(dx+dy)

C:\Users\ak954\AppData\Local\Temp\ipykernel_29936\4261408864.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(dx+dy)


array([[0.        ,        nan,        nan,        nan],
       [1.73205081, 0.        , 1.        , 1.        ],
       [1.41421356,        nan, 0.        , 0.        ],
       [1.41421356,        nan, 0.        , 0.        ]])

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [22]:
arr=np.random.randint(2,54,(4,4))
print(arr)
masked_arr=np.ma.masked_greater(arr,10)
np.sum(masked_arr)

[[47 33 49 13]
 [46 47  5 17]
 [23 47 53  6]
 [28  7 27 49]]


18

In [23]:
arr2=np.random.randint(3,13,(3,3))
arr2

array([[ 7,  3, 12],
       [ 6, 12, 11],
       [10,  8, 10]])

In [25]:
masked_arr=np.ma.masked_array(arr2,np.eye(3))
masked_arr

masked_array(
  data=[[--, 3, 12],
        [6, --, 11],
        [10, 8, --]],
  mask=[[ True, False, False],
        [False,  True, False],
        [False, False,  True]],
  fill_value=999999)

In [27]:
unmasked_mean=np.mean(masked_arr)
unmasked_mean


8.333333333333334

In [28]:
filled_arr=masked_arr.filled(unmasked_mean)

In [29]:
filled_arr

array([[ 8,  3, 12],
       [ 6,  8, 11],
       [10,  8,  8]])