# Numpy

NumPy is a fundamental library for scientific computing in python. it provides support for arrays and matrices ,along with a collection of mathematical functions to operate on these data structures. In this lesson ,we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [2]:
import numpy as np

## create array using numpy

#create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape((1,5)) # 1 row and 5 colums

array([[1, 2, 3, 4, 5]])

In [6]:
arr2.reshape((1,4))

ValueError: cannot reshape array of size 5 into shape (1,4)

In [ ]:
## 2d arra
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [13]:
np.arange(0,10,2) #(start,end,step)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(0,10,2).reshape(5,1) #(start,end,step)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3,4)) ## create 3*4 mat with all ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
##identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr=np.array([[1,2,3],[4,5,6]])
print("array", arr)
print("Shape : ",arr.shape)
print("number of dimension : ", arr.ndim) 
print("size (number of elements ) :", arr.size)
print("DatA Type : ", arr.dtype) ##output : int 64
print("item size (in bytes )", arr.itemsize)

array [[1 2 3]
 [4 5 6]]
Shape :  (2, 3)
number of dimension :  2
size (number of elements ) : 6
DatA Type :  int32
item size (in bytes ) 4


In [22]:
### Numpy Vectorized Operations
arr1=np.array([1,2,3,154,5])
arr2=np.array([10,20,30,40,25])

### Element wise addition
print("Addition : ", arr1+arr2)

## Element wise subtrafction
print("Multiplication" , arr1*arr2)

print("div",arr1//arr2)

Addition :  [ 11  22  33 194  30]
Multiplication [  10   40   90 6160  125]
div [0 0 0 3 0]


In [23]:
## Universal Functions

arr=np.array([1,2,3,4,5])

##sq root
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [24]:
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [25]:
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [26]:
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [29]:
## Array Slicing and Indexing 

arr=np.array([[1,2,3,4,5],[41,42,3,4,5],[3,5,4,2,1]])
arr


array([[ 1,  2,  3,  4,  5],
       [41, 42,  3,  4,  5],
       [ 3,  5,  4,  2,  1]])

In [30]:
arr[0][0]

1

In [31]:
arr[0]

array([1, 2, 3, 4, 5])

In [32]:
arr[1:]

array([[41, 42,  3,  4,  5],
       [ 3,  5,  4,  2,  1]])

In [33]:
arr[1:,2:]

array([[3, 4, 5],
       [4, 2, 1]])

In [38]:
print(arr[0:2,1:])

[[ 2  3  4  5]
 [42  3  4  5]]


In [39]:
## modify Array Elements 
arr[0,0]=100
print(arr)

[[100   2   3   4   5]
 [ 41  42   3   4   5]
 [  3   5   4   2   1]]


In [40]:
arr[1:]=100

In [41]:
arr

array([[100,   2,   3,   4,   5],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [44]:

## Statistical Concepts - Normalization  

## to have a mean of 0 and standard deviation of 1

data =np.array([1,2,3,4,5])

##calculating mean and standard deviation
std_dev=np.std(data)

mean=np.mean(data)

##normalized the data

norm_data=(data-mean)/std_dev
print("normalized data", norm_data)

normalized data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [47]:
print('mean: ',np.mean(data))
print("median: ", np.median(data))
print("variance :", np.var(data))


mean:  3.0
median:  3.0
variance : 2.0


In [52]:
##Logical Operation 

data=np.array([1,2,3,4,5,6,7,8,9,0])
data[(data>5) & (data <=8)]

array([6, 7, 8])

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [17]:
import numpy as np
arr=np.random.randint(1,9,(3,3))
arr

array([[6, 2, 3],
       [2, 3, 6],
       [3, 8, 8]])

In [18]:
entry=np.random.randint(1,6,size=(3,))
print(type(entry))

<class 'numpy.ndarray'>


In [20]:
res_rows=arr+entry
res_rows

array([[10,  4,  6],
       [ 6,  5,  9],
       [ 7, 10, 11]])

In [26]:
arr2=np.random.randint(1,9,(4,4))
entry=np.random.randint(1,5,size=(4,))
print(arr2,entry)
arr2+entry

[[8 6 4 8]
 [2 7 6 2]
 [5 5 1 7]
 [7 5 3 6]] [1 4 2 3]


array([[ 9, 10,  6, 11],
       [ 3, 11,  8,  5],
       [ 6,  9,  3, 10],
       [ 8,  9,  5,  9]])